### ISSUE TITLE
Allow rehydrating aggregate without updating

### ISSUE THREAD

**Issue by tgolden-andplus** [serialized-io/client-java#2]
Currently, the `AggregateClient` will rehydrate my aggregate type for me from the event stream.... *if* I am about to make an update to it. There doesn't seem to be any way to simply rehydrate the aggregate as-is (for example, I want to load the latest state from the event store in order to service a query). It _seems_ like I would want a method like `AggregateClient<T>.load(UUID id): T`, based on the underlying REST API: https://docs.serialized.io/api-reference/apis/event-sourcing/reference/load-all-events-for-an-aggregate

Is the assumption that all of my query methods should be served via Projections? It seems like I will duplicate a good amount of my logic from the aggregate *State class via JSONPath by doing so....

Alternatively, is the assumption that I am also subscribing via the Feeds client and updating a read model data store somewhere? e.g. by checking which events are emitted and deciding how to update my read model accordingly?

Some docs or examples would be useful. :) The Spring Boot sample app uses the Projections APIs for queries such as high score.

**Comment by mattiasholmqvist** [comment]
Hi,

Yes to serve queries you should use the projections client or the feeds client (to build a custom read model from your own server).

You _can_ however of course read all events using a plain HTTP client if you want to. The aggregate client is made stricter in this case since the aggregates API is not used supposed to be used for serving queries.

We're working on a more comprehensive Java guide that will be online shortly. Until then I suggest looking at the other examples [here](https://github.com/serialized-io/samples-java) too, but don't hesitate to ask if you have more questions.

**Comment by tgolden-andplus** [comment]
If I am using the FeedsClient to populate my own read model, how do I handle multiple instances of my application (which will create their own instance of the FeedsClient, and receive the same events from the store)?

Is there a mechanism to supply a client ID of some kind when subscribing to the feed, such that multiple subscribers with the same client ID do not read the same events? (Although even then, I would still be concerned about races while processing events belonging to the same aggregate between multiple consumers).

**Comment by jeham** [comment]
Hi!

This design is according to CQRS (i.e clear seggregation of the writing and reading part of an application). Think of the Aggregates API as the command/write-side of the system and the Projections/Feed API as the query/read-side. 

To be able to query a "current state" you should define a projection that dictates how the events should be merged into the complete and tailored read-model you need for your query case.

The easiest way would be to create a projection that simply merges all events, like this:

    projectionClient.createOrUpdate(singleProjection("orders")
        .feed("order")
        .addHandler(OrderPlacedEvent.class.getSimpleName(), merge().build())
        .addHandler(OrderCancelledEvent.class.getSimpleName(), merge().build())
        .addHandler(OrderFullyPaidEvent.class.getSimpleName(), merge().build())
        .addHandler(OrderShippedEvent.class.getSimpleName(), merge().build())
        .build());

Normally this would not lead to any logic duplication. The business logic needed for writing should be in the Aggregate class and would typically not be relevant when serving queries.

Check out this for a complete example: 
https://github.com/serialized-io/samples-java/tree/master/spark-todo-service

**Comment by jeham** [comment]
Although not recommended, you can hydrate the aggregate like this, eg. for testing purposes:

      myAggregateClient.update(aggregateId, hydratedState -> {
        ....
        // Return empty list to avoid update
        return Collections.emptyList();
      });

**Comment by jeham** [comment]
More advanced read-models, where the standard functions (https://docs.serialized.io/api-reference/apis/projections/event-handlers) are not enough, can be created using Custom functions, https://docs.serialized.io/api-reference/apis/projections/external-projector-functions

Or, like you mentioned, using a feed subscriber, if you wan't to hold the result in-memory or stored in a database of your choice.
